/**
 * Reading History Management
 * Saves readings to localStorage and provides sharing functionality
 */

import { SPREAD_TYPES } from './spread-types.js';

export class ReadingHistory {
  constructor() {
    this.storageKey = 'crypto_tarot_readings';
    this.maxReadings = 50; // Keep last 50 readings
  }

  // Save a reading
  saveReading(reading) {
    const readings = this.getAllReadings();
    const newReading = {
      id: Date.now().toString(),
      timestamp: new Date().toISOString(),
      question: reading.question || 'What does my crypto future hold?',
      cards: reading.cards,
      spreadType: reading.spreadType || '3-card',
      reading: reading.reading || null,
    };

    readings.unshift(newReading); // Add to beginning

    // Keep only the most recent readings
    if (readings.length > this.maxReadings) {
      readings.splice(this.maxReadings);
    }

    localStorage.setItem(this.storageKey, JSON.stringify(readings));
    return newReading;
  }

  // Get all readings
  getAllReadings() {
    try {
      const stored = localStorage.getItem(this.storageKey);
      return stored ? JSON.parse(stored) : [];
    } catch (e) {
      console.error('Error loading reading history:', e);
      return [];
    }
  }

  // Get a specific reading by ID
  getReading(id) {
    const readings = this.getAllReadings();
    return readings.find(r => r.id === id);
  }

  // Delete a reading
  deleteReading(id) {
    const readings = this.getAllReadings();
    const filtered = readings.filter(r => r.id !== id);
    localStorage.setItem(this.storageKey, JSON.stringify(filtered));
    return filtered;
  }

  // Clear all readings
  clearAll() {
    localStorage.removeItem(this.storageKey);
  }

  // Get reading count
  getCount() {
    return this.getAllReadings().length;
  }

  // Format reading for sharing
  formatForSharing(reading) {
    const date = new Date(reading.timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    let text = `🔮 Crypto Tarot Reading - ${date}\n\n`;
    text += `Question: "${reading.question}"\n`;
    text += `Spread: ${reading.spreadType}\n\n`;
    text += `Cards Drawn:\n`;

    const spread = SPREAD_TYPES?.[reading.spreadType];
    reading.cards.forEach((card, idx) => {
      const fallback = spread?.positions?.[idx];
      const position = card.position || fallback || `Position ${idx + 1}`;

      text += `\n${position}: ${card.title} (${card.orientation})\n`;
      const meaning = card.meaning || 'Card meaning';
      text += `Meaning: ${meaning}\n`;
    });

    text += `\n---\n`;
    text += `For entertainment purposes only. Not financial advice.`;
    text += `\nGenerated by Crypto Tarot 🔮`;

    return text;
  }

  // Copy reading to clipboard
  async copyToClipboard(reading) {
    const text = this.formatForSharing(reading);
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      try {
        document.execCommand('copy');
        document.body.removeChild(textarea);
        return true;
      } catch (err) {
        document.body.removeChild(textarea);
        return false;
      }
    }
  }
}

// Export singleton instance
export const readingHistory = new ReadingHistory();
